# This playbook is half-ass clone of the https://github.com/sleighzy/ansible-kafka playbook created as a test task.
# Nothing fancy was done here -- I am not the ansible expert.
---
- name: Install Apache Kafka to a single host
  hosts: default
  remote_user: root

- tasks

- name: Create kafka group
  group:
    name: '{{ kafka_group }}'
    state: present
  tags:
    - kafka_group

- name: Create kafka user
  user:
    name: '{{ kafka_user }}'
    group: '{{ kafka_group }}'
    state: present
    createhome: no
  tags:
    - kafka_user

- name: Check if Kafka has already been downloaded and unpacked
  stat:
    path: '{{ kafka_dir }}_{{ kafka_scala_version }}-{{ kafka_version }}'
  register: dir

- name: Download Apache Kafka
  get_url:
    url: https://apache-mirror.rbc.ru/pub/apache/kafka/{{ kafka_version }}/kafka_{{ kafka_scala_version }}-{{ kafka_version }}.ttgz
    dest: /tmp
  when: not dir.stat.exists
  tags:
    - kafka_download

- name: Unpack Apache Kafka
  unarchive:
    src: /tmp/kafka_{{ kafka_scala_version }}-{{ kafka_version }}.tgz
    dest: '{{ kafka_root_dir }}'
    copy: no
    group: '{{ kafka_group }}'
    owner: '{{ kafka_user }}'
  when: not dir.stat.exists
  tags:
    - kafka_unpack

- name: Create symlink to kafka installation directory
  file:
    src: '{{ kafka_root_dir }}/kafka_{{ kafka_scala_version }}-{{ kafka_version }}'
    dest: '{{ kafka_dir }}'
    state: link
    group: '{{ kafka_group }}'
    owner: '{{ kafka_user }}'
  tags:
    - kafka_dirs

- name: Create directory for kafka log files
  file:
    path: /var/log/kafka_"{{ item }}"
    state: directory
    group: '{{ kafka_group }}'
    owner: '{{ kafka_user }}'
  loop: "{{ kafka_broker_list }}"
  tags:
    - kafka_dirs

- name: Create directory for symlink to kafka configuration files
  file:
    path: /etc/kafka_"{{ item }}"
    state: directory
    group: '{{ kafka_group }}'
    owner: '{{ kafka_user }}'
  loop: "{{ kafka_broker_list }}"
  tags:
    - kafka_dirs
